/*
Webhooks API


Brex uses webhooks to send real-time notifications when events happen in the accounts that you manage.
Use webhook subscriptions to subscribe to different webhook events.


The version of the OpenAPI document: 0.1
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  WebhookSubscriptionsApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { BrexWebhooksCustom } from "./client-custom";

export class BrexWebhooks extends BrexWebhooksCustom {
  readonly webhookSubscriptions: WebhookSubscriptionsApi;

  constructor(configurationParameters: ConfigurationParameters) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.webhookSubscriptions = new WebhookSubscriptionsApi(configuration);
  }

}
