/*
Webhooks API


Brex uses webhooks to send real-time notifications when events happen in the accounts that you manage.
Use webhook subscriptions to subscribe to different webhook events.


The version of the OpenAPI document: 0.1
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { WebhookEventType } from './webhook-event-type';

/**
 * 
 * @export
 * @interface CreateWebhookSubscriptionRequest
 */
export interface CreateWebhookSubscriptionRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateWebhookSubscriptionRequest
     */
    'url': string;
    /**
     * The Brex API sends webhooks for the events listed below. For more details, see the [webhook guide](https://developer.brex.com/openapi/webhooks_api/) and [webhook events API reference](https://developer.brex.com/openapi/webhooks_api/).
     * @type {Array<WebhookEventType>}
     * @memberof CreateWebhookSubscriptionRequest
     */
    'event_types': Array<WebhookEventType>;
}

