/*
Webhooks API


Brex uses webhooks to send real-time notifications when events happen in the accounts that you manage.
Use webhook subscriptions to subscribe to different webhook events.


The version of the OpenAPI document: 0.1
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Money } from './money';

/**
 * 
 * @export
 * @interface ExpensePaymentStatusUpdatedEventAmount
 */
export interface ExpensePaymentStatusUpdatedEventAmount {
    /**
     * The amount of money, in the smallest denomination of the currency indicated by currency. For example, when currency is USD, amount is in cents.
     * @type {number}
     * @memberof ExpensePaymentStatusUpdatedEventAmount
     */
    'amount'?: number;
    /**
     * The type of currency, in ISO 4217 format. Default to USD if not specified
     * @type {string}
     * @memberof ExpensePaymentStatusUpdatedEventAmount
     */
    'currency'?: string | null;
}

