/*
Webhooks API


Brex uses webhooks to send real-time notifications when events happen in the accounts that you manage.
Use webhook subscriptions to subscribe to different webhook events.


The version of the OpenAPI document: 0.1
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ExpensePaymentStatus } from './expense-payment-status';
import { ExpensePaymentStatusUpdatedEvent } from './expense-payment-status-updated-event';
import { ExpensePaymentStatusUpdatedEventAmount } from './expense-payment-status-updated-event-amount';
import { ExpensePaymentType } from './expense-payment-type';
import { WebhookEventType } from './webhook-event-type';

/**
 * @type ExpensePaymentEvent
 * @export
 */
export type ExpensePaymentEvent = { event_type: 'EXPENSE_PAYMENT_UPDATED' } & ExpensePaymentStatusUpdatedEvent;


