/*
Webhooks API


Brex uses webhooks to send real-time notifications when events happen in the accounts that you manage.
Use webhook subscriptions to subscribe to different webhook events.


The version of the OpenAPI document: 0.1
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * `PURCHASE`: A pending transaction for making a purchase.  `REFUND`: A pending transaction for a refund.  `WITHDRAWAL`: A pending transaction for a withdrawal.  `DECLINED`: A pending transaction that was declined and will not be completed. 
 * @export
 * @enum {string}
 */
export type ExpensePaymentType = 'PURCHASE' | 'REFUND' | 'WITHDRAWAL' | 'DECLINED'

