/*
Webhooks API


Brex uses webhooks to send real-time notifications when events happen in the accounts that you manage.
Use webhook subscriptions to subscribe to different webhook events.


The version of the OpenAPI document: 0.1
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Only ACH, DOMESTIC_WIRE, CHEQUE, INTERNATIONAL_WIRE and BOOK_TRANSFER details can be retrieved from the Payments API.
 * @export
 * @enum {string}
 */
export type PaymentType = 'ACH' | 'DOMESTIC_WIRE' | 'CHEQUE' | 'INTERNATIONAL_WIRE' | 'BOOK_TRANSFER' | 'ACH_RETURN' | 'WIRE_RETURN' | 'CHEQUE_RETURN'

