/*
Webhooks API


Brex uses webhooks to send real-time notifications when events happen in the accounts that you manage.
Use webhook subscriptions to subscribe to different webhook events.


The version of the OpenAPI document: 0.1
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ApplicationStatus } from './application-status';

/**
 * 
 * @export
 * @interface ProductApplication
 */
export interface ProductApplication {
    /**
     * Application status of a product.  `NO_ACCOUNT` - There is no active application, and the product account is not provisioned.  `ACTIVE` - The application is approved, and the product account is provisioned.  `NOT_SUBMITTED` - The application is started but not yet submitted.  `INFORMATION_PENDING` - The application is submitted and additional information is requested.  `MANUAL_REVIEW` - The application is under manual review.  `PROCESSING` - The application is submitted and is under review.  `REJECTED` - The application is rejected.  `CLOSED` - The product account is closed. 
     * @type {ApplicationStatus}
     * @memberof ProductApplication
     */
    'cash': ApplicationStatus;
}

