/*
Webhooks API


Brex uses webhooks to send real-time notifications when events happen in the accounts that you manage.
Use webhook subscriptions to subscribe to different webhook events.


The version of the OpenAPI document: 0.1
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { WebhookEventType } from './webhook-event-type';

/**
 * The webhook will be sent when a user signs up with the referral link.
 * @export
 * @interface ReferralActivatedEvent
 */
export interface ReferralActivatedEvent {
    /**
     * 
     * @type {WebhookEventType}
     * @memberof ReferralActivatedEvent
     */
    'event_type': WebhookEventType;
    /**
     * 
     * @type {string}
     * @memberof ReferralActivatedEvent
     */
    'referral_id': string;
}

