/*
Webhooks API


Brex uses webhooks to send real-time notifications when events happen in the accounts that you manage.
Use webhook subscriptions to subscribe to different webhook events.


The version of the OpenAPI document: 0.1
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ProductApplication } from './product-application';
import { WebhookEventType } from './webhook-event-type';

/**
 * The webhook will be sent when the application status is changed.
 * @export
 * @interface ReferralApplicationStatusChangedEvent
 */
export interface ReferralApplicationStatusChangedEvent {
    /**
     * 
     * @type {WebhookEventType}
     * @memberof ReferralApplicationStatusChangedEvent
     */
    'event_type': WebhookEventType;
    /**
     * 
     * @type {string}
     * @memberof ReferralApplicationStatusChangedEvent
     */
    'referral_id': string;
    /**
     * 
     * @type {ProductApplication}
     * @memberof ReferralApplicationStatusChangedEvent
     */
    'application': ProductApplication;
}

