/*
Webhooks API


Brex uses webhooks to send real-time notifications when events happen in the accounts that you manage.
Use webhook subscriptions to subscribe to different webhook events.


The version of the OpenAPI document: 0.1
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ProductApplication } from './product-application';
import { ReferralActivatedEvent } from './referral-activated-event';
import { ReferralApplicationStatusChangedEvent } from './referral-application-status-changed-event';
import { ReferralCreatedEvent } from './referral-created-event';
import { WebhookEventType } from './webhook-event-type';

/**
 * @type ReferralEvent
 * @export
 */
export type ReferralEvent = { event_type: 'REFERRAL_ACTIVATED' } & ReferralActivatedEvent | { event_type: 'REFERRAL_APPLICATION_STATUS_CHANGED' } & ReferralApplicationStatusChangedEvent | { event_type: 'REFERRAL_CREATED' } & ReferralCreatedEvent;


