/*
Webhooks API


Brex uses webhooks to send real-time notifications when events happen in the accounts that you manage.
Use webhook subscriptions to subscribe to different webhook events.


The version of the OpenAPI document: 0.1
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PaymentType } from './payment-type';
import { WebhookEventType } from './webhook-event-type';

/**
 * The webhook will be sent when a transfer failed.
 * @export
 * @interface TransferFailedEvent
 */
export interface TransferFailedEvent {
    /**
     * 
     * @type {WebhookEventType}
     * @memberof TransferFailedEvent
     */
    'event_type': WebhookEventType;
    /**
     * 
     * @type {string}
     * @memberof TransferFailedEvent
     */
    'transfer_id': string;
    /**
     * Only ACH, DOMESTIC_WIRE, CHEQUE, INTERNATIONAL_WIRE and BOOK_TRANSFER details can be retrieved from the Payments API.
     * @type {PaymentType}
     * @memberof TransferFailedEvent
     */
    'payment_type': PaymentType;
    /**
     * The original transaction ID that is returned when the payment type is ACH_RETURN, WIRE_RETURN and CHEQUE_RETURN.
     * @type {string}
     * @memberof TransferFailedEvent
     */
    'return_for_id'?: string | null;
    /**
     *  This is the `id` returned in the [Get Company](https://developer.brex.com/openapi/webhooks_api/) endpoint. You can use the `company_id` to determine which access token to use when you get the details from our API endpoints. 
     * @type {string}
     * @memberof TransferFailedEvent
     */
    'company_id'?: string;
}

