/*
Webhooks API


Brex uses webhooks to send real-time notifications when events happen in the accounts that you manage.
Use webhook subscriptions to subscribe to different webhook events.


The version of the OpenAPI document: 0.1
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PaymentType } from './payment-type';
import { TransferFailedEvent } from './transfer-failed-event';
import { TransferProcessedEvent } from './transfer-processed-event';
import { WebhookEventType } from './webhook-event-type';

/**
 * @type TransferEvent
 * @export
 */
export type TransferEvent = { event_type: 'TRANSFER_FAILED' } & TransferFailedEvent | { event_type: 'TRANSFER_PROCESSED' } & TransferProcessedEvent;


