/*
Webhooks API


Brex uses webhooks to send real-time notifications when events happen in the accounts that you manage.
Use webhook subscriptions to subscribe to different webhook events.


The version of the OpenAPI document: 0.1
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { UpdateWebhookSubscriptionStatus } from './update-webhook-subscription-status';
import { WebhookEventType } from './webhook-event-type';

/**
 * 
 * @export
 * @interface UpdateWebhookSubscriptionRequest
 */
export interface UpdateWebhookSubscriptionRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateWebhookSubscriptionRequest
     */
    'url': string;
    /**
     * 
     * @type {Array<WebhookEventType>}
     * @memberof UpdateWebhookSubscriptionRequest
     */
    'event_types': Array<WebhookEventType>;
    /**
     * 
     * @type {UpdateWebhookSubscriptionStatus}
     * @memberof UpdateWebhookSubscriptionRequest
     */
    'status': UpdateWebhookSubscriptionStatus;
}

