/*
Webhooks API


Brex uses webhooks to send real-time notifications when events happen in the accounts that you manage.
Use webhook subscriptions to subscribe to different webhook events.


The version of the OpenAPI document: 0.1
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { UserAttributes } from './user-attributes';
import { WebhookEventType } from './webhook-event-type';

/**
 * The webhook will be sent when a user is updated.
 * @export
 * @interface UserUpdatedEvent
 */
export interface UserUpdatedEvent {
    /**
     * 
     * @type {WebhookEventType}
     * @memberof UserUpdatedEvent
     */
    'event_type': WebhookEventType;
    /**
     * 
     * @type {string}
     * @memberof UserUpdatedEvent
     */
    'user_id': string;
    /**
     * 
     * @type {string}
     * @memberof UserUpdatedEvent
     */
    'company_id': string;
    /**
     * 
     * @type {Array<UserAttributes>}
     * @memberof UserUpdatedEvent
     */
    'updated_attributes': Array<UserAttributes>;
}

