/*
Webhooks API


Brex uses webhooks to send real-time notifications when events happen in the accounts that you manage.
Use webhook subscriptions to subscribe to different webhook events.


The version of the OpenAPI document: 0.1
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { WebhookEventType } from './webhook-event-type';
import { WebhookSubscriptionStatus } from './webhook-subscription-status';

/**
 * 
 * @export
 * @interface WebhookSubscription
 */
export interface WebhookSubscription {
    /**
     * 
     * @type {string}
     * @memberof WebhookSubscription
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof WebhookSubscription
     */
    'url': string;
    /**
     * 
     * @type {Array<WebhookEventType>}
     * @memberof WebhookSubscription
     */
    'event_types': Array<WebhookEventType>;
    /**
     * 
     * @type {WebhookSubscriptionStatus}
     * @memberof WebhookSubscription
     */
    'status': WebhookSubscriptionStatus;
}

